set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "arm")
set(TARGET_TRIPLE "arm-linux-gnueabi")

set(CMAKE_C_COMPILER "${TARGET_TRIPLE}-gcc-14")
set(CMAKE_CXX_COMPILER "${TARGET_TRIPLE}-g++-14")
set(CMAKE_ASM_COMPILER "${TARGET_TRIPLE}-as")
set(CMAKE_AR "${TARGET_TRIPLE}-ar")
set(CMAKE_NM "${TARGET_TRIPLE}-nm")
set(CMAKE_RANLIB "${TARGET_TRIPLE}-ranlib")
set(CMAKE_STRIP "${TARGET_TRIPLE}-strip")
set(CMAKE_LINKER "${TARGET_TRIPLE}-ld")

