name: Build qat dependencies

on: workflow_dispatch

jobs:

  macos_arm64_icu4c:
    name: icu4c for macos_arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create directories
        run: |
          mkdir icu4c
          mkdir icu4c/arm64
          mkdir libs
          mkdir libs/icu4c
        
      - name: Download icu4c source
        working-directory: ./icu4c
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-77-1/icu4c-77_1-src.tgz
          tar -xzf icu4c-77_1-src.tgz

      - name: Build icu4c
        working-directory: ./icu4c/arm64
        run: |
          ../icu/source/configure --prefix="${{ github.workspace }}/libs/icu4c" --enable-static --disable-shared CFLAGS="-std=c11" CXXFLAGS="-std=c++20"
          make -j8
          sudo make install

      - name: Package icu4c
        working-directory: ./libs
        run: tar -cvzf icu4c_macos_arm64.tar.gz icu4c

      - name: Upload icu4c
        uses: actions/upload-artifact@v4
        with:
          name: icu4c_macos_arm64
          path: ${{ github.workspace }}/libs/icu4c_macos_arm64.tar.gz
