name: Test workflow

on:
  workflow_dispatch:
    inputs:
      llvmVersion:
        required: true
        default: "22.1.1"
        type: string
      boostVersion:
        required: true
        default: "1.90.0"
        type: string
      icuVersion:
        required: true
        default: "78.3"
        type: string

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create llvm${{ inputs.llvmVersion }}_boost${{ inputs.boostVersion }}_icu${{ inputs.icuVersion }} --title "llvm ${{ inputs.llvmVersion }}, boost ${{ inputs.boostVersion }}, icu4c ${{ inputs.icuVersion }}" --notes "Release notes are updated manually, so it is work in progress" --draft

  llvm_macos:
    name: LLVM for Windows (x64, win32, arm64)
    needs: [create_release]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set release name
        run: echo "RELEASE_NAME=llvm${{ inputs.llvmVersion }}_boost${{ inputs.boostVersion }}_icu${{ inputs.icuVersion }}" >> "$GITHUB_ENV"
      - name: Install Visual Studio Community
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.Windows11SDK.26100 --add Microsoft.VisualStudio.Component.Windows11SDK.22621 --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.Component.VC.ATL.ARM64 --add Microsoft.VisualStudio.Component.VC.MFC.ARM64" -y
      - name: Download LLVM source
        shell: bash
        run: |
          wget https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ inputs.llvmVersion }}.zip
          tar -xf llvm-project-${{ inputs.llvmVersion }}.src.tar.xz
          mv llvm-project-${{ inputs.llvmVersion }}.src llvm-project
          mkdir llvm

      - name: Build LLVM for x64
        working-directory: llvm-project/llvm
        shell: bash
        run: |
          cmake -S . -B "$GITHUB_WORKSPACE/llvm-project/llvm/build" -DCMAKE_BUILD_TYPE=Release -A x64 -G"Visual Studio 17 2022"

